Algoritmo "Antecessor"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/02/2023
Var
// Seção de Declarações das variáveis 
  N:Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite um número: ")
   Leia(N)
   Escreval("O antecessor de", N, " é", N - 1)
   Escreval("O sucessor de", N, " é", N + 1)

Fimalgoritmo