Algoritmo "Câmbio"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/02/2023
Var
// Seção de Declarações das variáveis 
  D:Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite um valor em Reais: ")
   Leia(D)
   Escreval("Com a quantia de R$", D, " vc pode comprar:", D*3.45, " dólares.")

Fimalgoritmo