Algoritmo "Conta1a10"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/03/2023
Var
// Seção de Declarações das variáveis 
   Cont: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
         Cont <- 1
         Repita
               EscrevaL(Cont)
               Cont <- Cont + 1
         Ate (Cont > 10)

Fimalgoritmo