Algoritmo "Dobro"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/02/2023
Var
// Seção de Declarações das variáveis 
  N:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite um núnero: ")
   Leia(N)
   Escreval("O dobro de", N, " é", N*2)
   Escreval("A terça parte de", N, " é", N/3)

Fimalgoritmo